name = "development"
main = "worker.js"
compatibility_date = "2025-08-04"
# type = "module"

# Development environment. Update IDs to "operation" environment IDs when ready for migration.
[[kv_namespaces]]
binding = "FLAGS"
id = "ae635740392a4962bbd823ee68b49b7d"

[[kv_namespaces]]
binding = "SETTINGS"
id = "5bbf361794f346459763e078f71f293a"

[vars]
DEV_ONLY = "true"
